site_name: SorusBoxScan
site_url: https://aferre88.github.io/5gdrone-docs/
theme:
  name: material
  features:
    - content.code.annotate
extra_javascript:
  - js/logos.js
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true